/*
 *  iron-man-helmet-controller
 *  Copyright (C) 2013 Roman Moravcik
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef VOICE_H
#define VOICE_H

#include <stdint.h>

enum {
	SOUND_IM_SUIT_01 = 0,
	SOUND_IM_SUIT_02,
	SOUND_IM_SUIT_03,
	SOUND_IM_SUIT_04,
	SOUND_IM_SUIT_05,
	SOUND_IM_SUIT_06,
	SOUND_IM_SUIT_07,
	SOUND_JARVIS_AFTERNOON,
	SOUND_JARVIS_ARC_REACTOR_MODE,
	SOUND_JARVIS_BATTERY_1,
	SOUND_JARVIS_BATTERY_2,
	SOUND_JARVIS_BATTERY_3,
	SOUND_JARVIS_BATTERY_4,
	SOUND_JARVIS_BATTERY_5,
	SOUND_JARVIS_BATTERY_6,
	SOUND_JARVIS_BATTERY_7,
	SOUND_JARVIS_BATTERY_8,
	SOUND_JARVIS_BATTERY_9,
	SOUND_JARVIS_BATTERY_10,
	SOUND_JARVIS_BATTERY_11,
	SOUND_JARVIS_BATTERY_12,
	SOUND_JARVIS_BATTERY_13,
	SOUND_JARVIS_BATTERY_14,
	SOUND_JARVIS_BATTERY_15,
	SOUND_JARVIS_BATTERY_16,
	SOUND_JARVIS_BATTERY_17,
	SOUND_JARVIS_BATTERY_18,
	SOUND_JARVIS_BATTERY_19,
	SOUND_JARVIS_BATTERY_20,
	SOUND_JARVIS_BATTERY_30,
	SOUND_JARVIS_BATTERY_40,
	SOUND_JARVIS_BATTERY_50,
	SOUND_JARVIS_BATTERY_60,
	SOUND_JARVIS_BATTERY_70,
	SOUND_JARVIS_BATTERY_80,
	SOUND_JARVIS_BATTERY_90,
	SOUND_JARVIS_BATTERY_100,
	SOUND_JARVIS_BATTERY_FULL_1,
	SOUND_JARVIS_BATTERY_FULL_2,
	SOUND_JARVIS_BATTERY_FULL_3,
	SOUND_JARVIS_BATTERY_LOW_1,
	SOUND_JARVIS_BATTERY_LOW_2,
	SOUND_JARVIS_BATTERY_LOW_3,
	SOUND_JARVIS_BATTERY_PERCENT,
	SOUND_JARVIS_BATTERY_POWER_AT,
	SOUND_JARVIS_EARLY_TO_RISE,
	SOUND_JARVIS_EVENING,
	SOUND_JARVIS_FULL_ARMOR_MODE,
	SOUND_JARVIS_MORNING,
	SOUND_JARVIS_REPULSOR_POWERED,
	SOUND_JARVIS_RISE_AND_SHINE,
	SOUND_JARVIS_SCREEN_ON,
	SOUND_JARVIS_TIME_TO_GET_UP_SLEEPY,
	SOUND_JARVIS_TIME_TO_GET_UP,
	SOUND_JARVIS_WAKE_UP,
	SOUND_JARVIS_WEATHER_CLEAR,
	SOUND_JARVIS_WEATHER_COLD,
	SOUND_JARVIS_WEATHER_HOT,
	SOUND_JARVIS_WEATHER_RAIN,
	SOUND_JARVIS_WEATHER_SNOW,
	SOUND_REPULSOR
};

enum {
	SOUND_VOLUME_0 = 0xE0,
	SOUND_VOLUME_1,
	SOUND_VOLUME_2,
	SOUND_VOLUME_3,
	SOUND_VOLUME_4,
	SOUND_VOLUME_5,
	SOUND_VOLUME_6,
	SOUND_VOLUME_7,
};

void voice_init(void);

void voice_play_sound(uint8_t sound);
void voice_play_sound_no_wait(uint8_t sound);

void voice_set_volume(uint8_t volume);

#endif // VOICE_H
